### ISSUE TITLE
All values in #TempDB_Files_SpaceUsage for templog.ldf is null

### ISSUE THREAD

**Issue by GovindRulz** [aleksey-vitsko/Database-Administrator-Tools#1]
Hi, your script was exactly what i was looking for to understand the working of Tempdb. recently ran into the issue of the log file becoming full twice in a single day.  When i ran the script all the values in the table #TempDB_Files_SpaceUsage for templog.ldf was showing null except for the first 3 columns

**Comment by aleksey-vitsko** [comment]
Hello, glad it helps! if you could post a screenshot showing what exactly is missing, that would be great

**Comment by aleksey-vitsko** [comment]
> Hi, your script was exactly what i was looking for to understand the working of Tempdb. recently ran into the issue of the log file becoming full twice in a single day. When i ran the script all the values in the table #TempDB_Files_SpaceUsage for templog.ldf was showing null except for the first 3 columns

Hello, glad it helps! if you could post a screenshot showing what exactly is missing, that would be great

**Comment by aleksey-vitsko** [comment]
@GovindRulz  Hi, let me know if you have additional details for this issue requested above, I'll wait until end of next week, and then close the issue if no updates, Thanks!
