### ISSUE TITLE
DatabaseSpaceUsage should take @databaseName in square brackets

### ISSUE THREAD

**Issue by kinguru** [aleksey-vitsko/Database-Administrator-Tools#2]
Hello Aleksey, 

I have production db name like "A.B.C" - containing 3 dots in the name.
The script DatabaseSpaceUsage fails with error "[The object name contains more than the maximum number of prefixes. The maximum is 3".
It will work in case the stored procedure will use databaseName like `FROM ['+ @databaseName +']`

Kind regards,
Ilya

**Comment by aleksey-vitsko** [comment]
@kinguru thanks for pointing that out! I'll try to fix this week

**Comment by aleksey-vitsko** [comment]
@kinguru updated the stored procedure, try it and let me know if it works on your db

exec DatabaseSpaceUsage @databaseName = 'A.B.C'

**Comment by aleksey-vitsko** [comment]
@kinguru did updated sp work for you ?

**Comment by kinguru** [comment]
Sorry, was busy with my work. Will check in nearest days

**Comment by kinguru** [comment]
thanks, it's working!
