### ISSUE TITLE
Arithmetic overflow error from MemoryManagerInfo

### ISSUE THREAD

**Issue by Crazyleofeng** [aleksey-vitsko/Database-Administrator-Tools#3]
pct					decimal(5,2),
would update to 
	pct					decimal(7,2),

e.g.: my sql server:
  Maximum Workspace Memory (KB): 91956240
  Total Server Memory (KB): 4544664

SO: 
select CAST(91956240.00 / 4544664.00 * 100 as   decimal(5,2))           
will pop up error: 
Arithmetic overflow error converting numeric to data type numeric.

![image](https://github.com/aleksey-vitsko/Database-Administrator-Tools/assets/11804571/bb54658b-33d0-48cc-86ce-c9d30acd0c00)

**Comment by aleksey-vitsko** [comment]
Hi @Crazyleofeng , I'll check next week

**Comment by aleksey-vitsko** [comment]
@Crazyleofeng could you please share, what is your:
1. SQL Server version / edition
2. What's total amount of RAM on a server ?
3. What is your Max Server Memory setting (select * from sys.configurations where [name] like '%max%server%memory%')  
4. And what is your Target Server Memory (KB)  (select * from sys.dm_os_performance_counters where counter_name like '%Target Server Memory%')   ?

**Comment by Crazyleofeng** [comment]
> @Crazyleofeng could you please share, what is your:
> 
> 1. SQL Server version / edition
A: 13.00.6404 / Enterprise 
> 2. What's total amount of RAM on a server ?
A: 128GB
> 3. What is your Max Server Memory setting (select * from sys.configurations where [name] like '%max%server%memory%')
A: 
![image](https://github.com/aleksey-vitsko/Database-Administrator-Tools/assets/11804571/32f295f8-a5b4-4ef5-8a26-31715a4d50e6)

> 4. And what is your Target Server Memory (KB)  (select * from sys.dm_os_performance_counters where counter_name like '%Target Server Memory%')   ?
![image](https://github.com/aleksey-vitsko/Database-Administrator-Tools/assets/11804571/d96562b4-c181-4962-8366-236ebf9ca9f2)


Thanks for your great work!
